version: '3'

services:

  postgres:
    image: littlebobbytables/postgres-pg_similarity
    environment:
      - POSTGRES_USER=fanuniverse
      - POSTGRES_PASSWORD=fanuniverse
    volumes:
    - ./tmp/postgresql/data/:/var/lib/postgresql/data
    ports:
      - "localhost:5434:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms768m -Xmx768m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "localhost:9200:9200"

  redis:
    image: redis:4.0-alpine
    ports:
      - "localhost:6379:6379"

  nginx:
    image: nginx:1.13-alpine
    depends_on:
      - malachite
      - camo
    volumes:
      - ./priv:/priv
      - ./priv/devserver.nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "localhost:80:80"

  malachite:
    # Exposed through NGINX
    image: littlebobbytables/malachite:latest
    environment:
      - CAMO_HOST=http://client.lvh.me/camo
      - CAMO_KEY=dev-camo-key

  camo:
    # Exposed through NGINX
    image: littlebobbytables/camo:latest
    environment:
      - CAMO_KEY=dev-camo-key

  sapphire:
    image: littlebobbytables/sapphire:latest
    ports:
      - "localhost:3030:3030"
    environment:
      - REDIS_HOST=redis

  vidalia:
    image: littlebobbytables/vidalia:latest
    ports:
      - "localhost:3040:3030"
    cap_drop: [DAC_OVERRIDE, FOWNER, CHOWN, SETGID, SETUID,
               SETPCAP, NET_BIND_SERVICE, SYS_CHROOT, MKNOD]
